dateformat: '%Y%m%d'

# 下单服务器端的对应的客户端配置
broker_client:
        host: 'xxxxxx' # 远端服务器的IP或者域名
        url: '/api'
        port: 8080
        token: 'xxxxxxxxxxxxxxxxxx' # 这个和下面的下单服务器的token一致就好，自己随意定义

notification: # level: ERROR,INFO是分开的，而不是传统意义上包含的关系，这样做是为了方便分开通知和报警
        - weixin: # 企业微信
           -
             name: '通知群'
             url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxx'
             level: 'INFO'
           -
             name: '警告群'
             url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxx'
             level: 'ERROR,WARN'
           -
             name: '信号群'
             url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxx'
             level: 'SIGNAL'
        - email: # 邮件
           -
             name: '我的邮箱'
             url: 'xxxxxxxxx@qq.com'
             level: 'INFO,ERROR,WARN'

email:
    name: '我的qq邮箱'
    host: 'smtp.qq.com'
    uid: 'xxxxxxxxx@qq.com'
    pwd: 'xxxxxxxxxxxx'

# -------- 以下为服务器配置，懒得分开了，放一起吧 ---------

# 下单服务器的配置
broker_server:
        token: 'xxxxxxxxxxxxxxxxxx'
        port: 8080

# 当前使用的券商
broker:
        name: 'qmt'
        buy_limit: 0.05 # 超过5%的涨幅就不买了
        sell_limit: 0.05# 超过5%的跌幅就不卖了

scheduler:
        heartbeat: # 客户端配置
            interval: 30 # 多久检查一次，单位是分钟
            services:
              -
                name: 'server' # 服务器的心跳
                timeout: 30 # 30分钟过期，单位是分钟
                check_time: 9:30~15:00 # 检测时间
              -
                name: 'qmt' # qmt软件的心跳
                timeout: 30 # 30分钟过期，单位是分钟
                check_time: 9:30~15:00 # 检测时间

heartbeat:
        interval: 300 # 发送心跳的间隔，单位是秒
        dir: # 发送心跳的文件夹
          - 'data/etf'
etf:
    dir: 'data'
    svg_path: 'data/etf.svg'
    jpg_path: '/static/img/etf.jpg'